# Generated by Django 3.0.5 on 2021-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('advise', models.TextField(default='Not Yet Added')),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='doctor', max_length=100)),
                ('Password', models.CharField(default='1234', max_length=50)),
                ('image', models.FileField(default='defaults.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('image', models.FileField(default='defaults.jpg', max_length=255, upload_to='')),
                ('age', models.CharField(default='0', max_length=10)),
                ('BloodGroup', models.CharField(default='0', max_length=10)),
                ('doctor', models.CharField(default='Doctor', max_length=50)),
                ('height', models.CharField(default='0cm', max_length=10)),
                ('weight', models.CharField(default='0kg', max_length=5)),
                ('address', models.CharField(default='0', max_length=255)),
                ('checkup', models.DateField(blank=True, null=True)),
                ('BP', models.CharField(default='Not Yet', max_length=255)),
                ('glucose', models.CharField(default='Not Yet', max_length=255)),
                ('sugar', models.CharField(default='No', max_length=255)),
                ('healthissue', models.CharField(default='Patient', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('doctor', models.CharField(default='Doctor', max_length=255)),
                ('prescription', models.TextField(default='Not Yet Added')),
                ('image', models.FileField(default='defaults.jpg', upload_to='')),
            ],
        ),
    ]
