# Generated by Django 3.0.5 on 2021-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210625_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='hospital',
            field=models.CharField(default='Hospital', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(default='Not Yet', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(default='Not Yet', max_length=255),
        ),
    ]
