# Generated by Django 3.0.5 on 2021-05-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210523_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_code',
            new_name='Password',
        ),
    ]
