# Generated by Django 3.0.5 on 2021-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210523_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.TextField(max_length=10),
        ),
    ]
