# Generated by Django 3.0.5 on 2021-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210525_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
