# Generated by Django 3.0.5 on 2021-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210525_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='images/'),
        ),
    ]
