# Generated by Django 3.0.5 on 2021-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='C:/Users/Amutha/myproject/media/download.jpg', upload_to='media/'),
        ),
    ]
