# Generated by Django 3.0.5 on 2021-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='media/download.jpg', null=True, upload_to='media/'),
        ),
    ]
