# Generated by Django 3.0.5 on 2021-05-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210531_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='download/random.png', null=True, upload_to='image/'),
        ),
    ]
