# Generated by Django 3.0.5 on 2021-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20210531_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default/random.png', upload_to='C:/Users/Amutha/myproject/images/'),
        ),
    ]
