# Generated by Django 3.0.5 on 2021-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20210531_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default/random.png', max_length=255, upload_to='C:/Users/Amutha/myproject/images/'),
        ),
    ]
