# Generated by Django 3.0.5 on 2021-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default='default/random.png', max_length=255, upload_to='images/%Y/%m/%d/'),
        ),
    ]
