# Generated by Django 3.0.5 on 2021-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20210531_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default='download.jpg', max_length=255, upload_to='mymedia/'),
        ),
    ]
