# Generated by Django 3.0.5 on 2021-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20210531_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default='download.jpg', max_length=255, upload_to=''),
        ),
    ]
