# Generated by Django 3.0.5 on 2021-06-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_auto_20210531_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default='defaults.jpg', max_length=255, upload_to=''),
        ),
    ]
