# Generated by Django 3.0.5 on 2021-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='qty',
        ),
        migrations.AddField(
            model_name='doctors',
            name='Password',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AddField(
            model_name='doctors',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
