

from . import views
from django.urls import path

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.register,name="register"),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name="logout"),
    path('upload/',views.image_view,name="image_view"),
    path('uploaded/', views.image_upload_view,name="image_upload_view"),
    path('profile/',views.profile,name='profile'),
    path('profiles/',views.profiles,name='profiles'),
    path('myprofile/',views.myprofile,name='myprofile'),
    path('myprofiles/<int:id>/',views.myprofiles,name="myprofiles"),
    path('doctor/login/',views.doctor,name='doctor'),
    path('doctor/profile/',views.doctorlogin,name='doctorlogin'),
    path('doctor/addprescription/<int:id>/',views.addprescription,name='addprescription'),
    path('doctor/patients/<int:id>/',views.docpatients,name="doctpatients"),
    path('doctor/logout/',views.doclogout,name='doclogout'),
    path('doctor/addprescriptions/<int:id>',views.addedprescription,name='addedprescription'),
    path('doctor/profiles/',views.doctorprofile,name="doctorprofile"),
    path('doctor/myprofile/',views.dochome,name="dochome"),
    path('doctor/myprofile/update/',views.docpassupdate,name="docpassupdate"),
    path('doctor/myprofile/error/',views.doctorpassupdate,name="doctorpassupdate"),
    path('doctor/myprofile/pass/',views.docpass,name="docpass"),
    path('admin/logining/',views.admin,name="admin"),
    path('admin/profile/',views.adminprofile,name="adminlogin"),
    path('admin/logouts/',views.adminlogout,name="adminlogout"),
    path('updatepass/<int:id>/',views.updatepass,name="updatepass"),
    path('updated/<int:id>/',views.updatedpass,name="updatedpass"),
    path('doctor/myprofile/<str:username>/',views.docmyprofile,name="docmyprofile"),
    path('doctor/myprescriptions/',views.myprescription,name="myprescription"),
    path('reports/<str:fullname>/',views.reports,name="reports"),
    path('doctor/addadvise/<int:id>/',views.addadvise,name="addadvise"),
    path('doctor/addedadvise/<int:id>/',views.addedadvise,name="addedadvise"),
    path('admin/viewpatients/',views.viewuser,name="viewuser"),
    path('admin/updatepatients/',views.updateuser,name="updateuser"),
    path('admin/patients/update/<int:id>/',views.updateuserpage,name="updateuserpage"),
    path('admin/patients/updated/<int:id>/',views.updateuserfunc,name="updateuserfunc"),
    path('admin/patients/',views.createuser,name="createuser"),
    path('admin/createdpatients/',views.createuserfunc,name="createuserfunc"),
    path('admin/created/',views.createduser,name="createduser"),
    path('admin/viewdoctor/',views.viewdoc,name="viewdoc"),
    path('admin/createddoctor/',views.createdoctorfunc,name="createdoctorfunc"),
    path('admin/doctor/',views.createdoctor,name="createdoctor"),
    path('admin/createddoc/',views.createddoctor,name="createddoctor"),
    path('admin/view/',views.viewadmin,name="viewadmin"),
    path('admin/admin/',views.createadmin,name="createadmin"),
    path('admin/createdadmins/',views.createadminfunc,name="createadminfunc"),
    path('admin/admincreated/',views.createdadmin,name="createdadmin"),
    path('admin/deletepatients/',views.deleteuser,name="deleteuser"),
    path('admin/deletepatientfunc/<int:id>/',views.deletuserfunc,name="deleteuserfunc"),
    path('admin/deletedpatient/',views.deleteduser,name="deleteduser"),
    path('admin/deletedoctor/',views.deletedoctor,name="deletedoctor"),
    path('admin/deletedoctorfunc/<int:id>/',views.deletedoctorfunc,name="deletedoctorfunc"),
    path('admin/deleteddoctor/',views.deleteddoctor,name="deleteddoctor"),
    path('admin/deleteadmin/',views.deleteadmin,name="deleteadmin"),
    path('admin/deleteadminfunc/<int:id>/',views.deleteadminfunc,name="deleteadminfunc"),
    path('admin/deletedadmin/',views.deletedadmin,name="deletedadmin"),
    path('admin/updatedoctor/',views.updatedoctor,name="updatedoctor"),
    path('admin/updatedocpage/<int:id>/',views.updatedocpage,name="updatedocpage"),
    path('admin/updatedocfunc/<int:id>/',views.updatedocfunc,name="updatedocfunc"),
    path('mydoctor/<str:doctor>/',views.mydoctor,name="mydoctor"),
    path('admin/updatepassadmin/',views.updatepassadmin,name="updatepassadmin"),
    path('admin/updatedpassadmin/',views.updatedpassadmin,name="updatedpassadmin"),
    path('admin/updatepasserror/',views.updatepasserror,name="updatepasserror"),
    path('forgotpassword/',views.forgotpass,name="forgotpass"),
    path('forgotpassword/sent/',views.forgotpasssent,name="forgotpasssent"),
    path('changepassword/',views.changepassword,name="changepassword"),
    path('changedpassword/',views.changedpassword,name="changedpassword"),
    path('prescription/<str:username>/',views.docprescription,name="docprescription"),
    path("admin/home/",views.adminhome,name="adminhome"),
    path('admin/forgot_password/',views.adminforgotpass),
    path('admin/forgot_password/sent/',views.adminforgotpasssent),
    path('admin/changepassword/',views.adminchangepassword),
    path('admin/changedpassword/',views.adminchangedpassword),
    path('doctor/forgot_password/',views.doctorforgotpass),
    path('doctor/forgot_password/sent/',views.doctorforgotpasssent),
    path('doctor/changepassword/',views.doctorchangepassword),
    path('doctor/changedpassword/',views.doctorchangedpassword)
]

